### ISSUE TITLE
NRJ int + Faux choix

### ISSUE THREAD

**Issue by gldlv** [FranceRose/rpg_tif#2]
Il y a quelques problèmes mineurs mais à régler quand même sur la première partie. Ex: 

- Des choix mal répertoriés (Tiphaine dit qu'elle veut gueuler contre le mail d'Auguste, mais finalement ça ne gueule pas)
- Une exception levée sur le calcul de l'énergie lors de la conversation avec France

J'ai aussi l'impression que certaines actions font gagner de l'NRJ alors qu'elles ne devraient peut-être pas ? (Ex: Tiphaine analyse les données)

Je mets le log de la partie en question:

-----------------------------------------------------------------------------------------------------

pyxis@pyxis-W65-W67RC:~/GitHub/rpg_tif$ python rpg.py 
 In a near Future, not so far away...

MBTI WARS
Episode LXIV

THE RISE OF TIPHAINE CHAMPETIER

--------------------------------------------------------------------------------

Pandémie ! En ce mois de Juillet 2022, le coronavirus a muté en une forme encore
plus mortelle et gravissime.

L’IBENS rappelle ses personnels de par le monde. Ancien.ne.s doctorant.e.s et
post-doctorant.e.s désoeuvré.e.s de toute la galaxie sont appelé.e.s à leur
bureau afin de poursuivre la lutte.

Par le dernier vol air-France avant la faillite de la compagnie, Tiphaine
Champetier quitte son élevage de chèvres des montagnes du Pakistan où elle
s'était réfugiée, et regagne Paris.

Immédiatement, on l'y enjoint à reprendre son travail de Deep Learning, afin de
développer de nouveaux tests diagnostics en distinguant les cellules infectées
des non-infectées.

Bien qu’elle retrouve à l'IBENS tous ses anciens collègues, beaucoup de choses
ont changé depuis son départ...

L’éminent professeur Ridier Daoult, nouveau directeur de l’institut, a fait main
basse sur ses ressources et utilise désormais à des fins personnelles
l’intégralité du deuxième étage pour la fabrication d’un nouveau remède miracle
sous la forme d’un breuvage sucré : le corona-cola.

Le bruit court que le très revanchard Pierre Paoletti, appuyé par la résistance,
tente de saper la sortie mondiale imminente du corona-cola. Convaincue du
bien-fondé de leur lutte, et persuadée de trouver là un vivier de personnes
réceptives à ses prosélytismes, Tiphaine se met en tête de les aider.

Mais le temps presse !

Ce Jeudi 14 Juillet 2022, le président nouvellement élu Jean Lasalle prévoit en
effet d'effectuer avec Daoult le lancement mondial du corona-cola pour la fête
nationale. Tiphaine doit agir, et vite.

Après 2 années de fermage, c'est étrange de se sentir propre à nouveau. C'est étrange de porter de vraies chaussures aussi.

Le front collé au hublot de l'avion, Tiphaine contemple pour une dernière fois les montagnes du Pakistan, où elle s'était
réfugiée après sa thèse, et qu'elle quitte maintenant à regret. Elle repense à ses chèvres, qu'elle a vendues pour acheter
son billet pour Paris et à son djembé. Il faudra qu'elle s'en rachète un une fois de retour en France d'ailleurs, pour
la fête de l'Huma en septembre ! Enfin... Si elle est encore vivante en septembre. Et s'il y a une fête de l'Huma en Septembre.
Et s'il reste des vendeurs de djembé d'ici septembre... Tiphaine se dit que la situation est déprimante. Elle repense à son
village d'accueil. Ce qui lui manquera le plus, sûrement, c'est le scrutin majoritaire qu'elle avait réussi à y négocier.

L'hôtesse de l'air passe dans les rangs et propose à tou.te.s une boisson. Quand elle arrive à sa hauteur, Tiphaine la rembarre
sèchement :
Est-ce qu'il ne serait pas temps en 2022 d'arrêter de servir de l'eau dans un gobelet à usage unique ? Franchement ?
Est-ce qu'on ne pourrait pas ENFIN autoriser les gens à prendre leur gourde en alu dans l'avion pour ne pas gâcher de plastique ?
C'est parce qu'on vient du Pakistan c'est ça ? On est forcément des terroristes ? A quoi ça sert de faire des conférences
citoyennes sur le climat si c'est pour boire dans des gobelets en plastique ?

Son voisin lui répond que si elle a une conscience écologique, elle devrait peut-être arrêter de prendre l'avion. Elle
l'ignore. C'est sûrement juste une sorte de connard.

Drôle d'époque quand même ! Elle qui avait fait le voyage aller en vélo pendant
des mois, c'est vrai qu'elle prend maintenant l'avion pour le retour en quelques
heures à peine... Mais il faut dire que tout est différent à présent. Avec l'effondrement
mondial du trafic aérien due au COVID-22, le secteur représente à nouveau une toute petite
part des émissions mondiales. Est-ce qu'on ne peut pas dire que Tiphaine est redevenue
un Epsilon dans toute cette histoire ? Elle se réconforte à cette pensée douce:
Elle n'est qu'un epsilon.

Elle regarde les nuages à présent. Ils ont l'air duveteux. Cela lui donne envie
de dormir. Et elle dort.

A Roissy elle se réveille à peine. On lui donne une fiche d'informations sur le
COVID-22, qu'elle ne prend pas la peine de lire, car elle ne croit pas aux consignes
du gouvernement. Elle croit comprendre que pendant qu'elle était en exil, Jean
Lasalle a été élu Président de la République aux élections 2022... Elle n'ose
pas y croire et pourtant, les kiosques à journaux semblent formel.

C'est une bonne nouvelle, car Lasalle est un berger ! Comme elle à présent ! Le
monde a bien changé... Un peu en mal, mais peut-être aussi en bien.

Elle franchit un dernier portique. Il y a peu de sécurité pour une avant-veille
de 14 Juillet. Deux CRS la croisent en l'ignorant royalement. Elle aurait aimé
avoir un prétexte pour se fighter avec eux, mais malheureusement ils ont l'air
de ne pas la calculer.

Arrivée dehors, un taxi automatique s'arrête pour elle devant l'aéroport presque
désert. Elle grimpe et rentre sur la tablette utilisateur l'adresse son ancien
appartement. Sur le trajet les rues de Paris sont désertes, comme l'aéroport,
et des arroseurs automatiques y pulvérisent en permanence de l'eau de javel diluée.
Il n'y a pas plus de monde dans les rues que sur les cimes célestes du Karakoram.

Les paysages gris défilent. Que va-t-elle bien pouvoir faire en arrivant ? Adrien
est confiné aux Pays-Bas. Moby a été surpris par la rapidité de mise en place du
confinement et il est coincé dans sa chambre d'hôtel aux Canaries, qu'il partage
péniblement avec trois candidates de Miss France qui venaient tourner l'épreuve
de frisbee et volley sur plage - la nouvelle lubie du comité Miss France pour
remplacer habilement l'épreuve des maillots de bain qui ne passe plus en 2022.
Quand elle y pense, elle a un peu le seum de la vie. Elle aimerait le bombarder
de messages pour savoir si elles ont pris autre chose que des bikini dans leurs
valises au moins, ou pour qu'il la rassure en lui disant qu'elles jouent très mal
au frisbee. Mais hélas elle vit désormais dans un mode low-tech et n'a pas de
téléphone. La voiture s'arrête devant son ancien immeuble. Elle ne prend pas le
temps d'admirer le paysage désert. Elle monte.

Immédiatement elle s'y sent en sécurité. Chez elle. Elle a l'impression que rien
n'a changé. Elle s'affale sur le canapé, et programme un réveil à 8h,
persuadée qu'elle arrivera à se lever. Elle sombre dans un sommeil profond.

TUTORIEL:

Tiphaine a beaucoup de courage. Mais Tiphaine n'a pas beaucoup d'#NRJ. Ou,
pour être plus précis, Tiphaine a besoin de SIESTER souvent pour avoir de
l'#NRJ.

Au cours de son aventure, Tiphaine pourrait mourir d'épuisement si elle ne fait
pas suffisamment attention à son #NRJ. Tandis qu'elle vient d'arriver à Paris,
elle doit contre-carrer les plans de Daoult concernant le corona-cola.

Elle doit faire attention au #TEMPS, car elle ne dispose pour cela que d'une
journée. Cette journée commence à 8h et se termine à 22h.

********************************************************************************
**           Il est 8h00. Il te reste 100 d'#NRJ.
********************************************************************************

BIP BIP BIP BIP
BIP BIP BIP BIP

..... Tiphaine entre-ouvre les yeux.
Un camion-poubelle passe.

C'est bon signe, ça veut dire qu'il reste encore des éboueurs en vie.

Pendant un instant Tiphaine se rassure. Elle a fait un cauchemar où une pandémie
décimait toute l'humanité ! Sauf que...  En fait, c'est vrai :(

Paris. Nous sommes le Mercredi 13 Juillet 2022, il est 8h.
Le réveil sonne.

Il faut 1h pour aller au labo. Que faire ?
De votre choix dépendra votre #NRJ

--------------------------------------------------------------------------------

SNOOZE :
8h ? C'est pas interdit par la convention de Genève de se lever à 8h ?

SE LEVER:
Ca va faire 2 ans que je me lève à 4h du matin. Allez, je me lève ! [50% succès]

--------------------------------------------------------------------------------

Snooze ? (T/F)
 
Ta réponse n'est pas reconnue. [T/F]
T
********************************************************************************
**           Cette action t'a pris 60 minutes et tu as perdu 0 point(s) d'#NRJ.
********************************************************************************

La fonction Snooze est faite pour qu'on l'utilise, non ?

********************************************************************************
**           Il est 9h00. Il te reste 100 d'#NRJ.
********************************************************************************

Tandis que Tiphaine approche l’IBENS, un automobiliste a garé son gros Hummer 4x4 sur une piste cyclable
en double file devant une boutique de montres de luxes.

--------------------------------------------------------------------------------

LUI FAIRE UN SERMON :
Cet automobiliste ne comprend vraiment pas la fonction d'une piste cyclable ! Non mais !
Et en 2022, avoir la conscience écologique d'une huître, ça ne devrait pas être permis !

LAISSER COULER :
Celui-là mérite vraiment une claque et un livre de Nicolas Hulot, mais le Covid n'attend pas,
ça sera pour un autre jour.

--------------------------------------------------------------------------------

Sermon ? (T/F)T
********************************************************************************
**           Cette action t'a pris 15 minutes et tu as gagné 3 point(s) d'#NRJ.
********************************************************************************

Tu t'es engagée dans une joute verbale avec le chauffeur, une bonne chose de faîte (ou pas) !

En partant, tu ne résistes pas à l'envie de mettre un coup de pied dans le rétro.
Ah ça t'avait manqué ce boost d'adrénaline quotidien :p

********************************************************************************
**           Il est 9h15. Il te reste 100 d'#NRJ.
********************************************************************************

Tiphaine arrive comme une fleur à pas d'heure dans le hall de l'IBENS.

Comme d'hab.

Là, elle croise Swann. Très contente de la revoir, elle papote 
quelques instants avec elle.

Tiphaine lui raconte les montagnes du Pakistan. Les chèvres. 

Après quelques minutes, Swann lui propose :
On va quand même pas rester plantées là ! Il est passé 9h. Allons boire un verre !

Tiphaine refuse, puis se laisse convaincre. 
Une bonne binouze ça n'a jamais tué personne. Allons chez Youssef !

--------------------------------------------------------------------------------

Chez Youssef, Swann explique tout ce qui a changé en deux ans.

Daoult est maître de l'institut. Il prépare la sortie mondiale du corona-cola.

C'est un vrai maniaque de l'organisation: Il est clairement ESTJ !

Tiphaine se dit que cette information pourrait être cruciale pour vaincre Daoult.

Après quasiment 1 heure de bavardage bien dépensée, Tiphaine retourne dans le hall de l'IBENS.

********************************************************************************
**           Cette action t'a pris 45 minutes et tu as perdu 0 point(s) d'#NRJ.
********************************************************************************
********************************************************************************
**           Il est 10h00. Il te reste 100 d'#NRJ.
********************************************************************************

Impossible d’accéder à son bureau sans badge.

--------------------------------------------------------------------------------

Tiphaine demande à ce qu’on lui ouvre la porte de la cafet. Elle arrive ensuite à la porte
de SYSINFO.

Arrivée à SYSINFO, elle croise Pierre Vincens. Il ne veut pas ouvrir la porte
pour respecter les gestes barrières.

D'ailleurs, il y a littéralement une barrière pour bloquer le passage.

--------------------------------------------------------------------------------

INSISTER :
"Promis, je garde mon masque, je reste à la porte du bureau et je mets deux fois
du gel hydroalcoolique en frottant 60 secondes - pas moins." [50% succès]

ATTENDRE :
"Je repasserai plus tard. Merci..."

--------------------------------------------------------------------------------

Insister ? (T/F)

T

P.V hésite, puis fait rentrer Tiphaine.

Ah là là! 

Depuis que le plan CovIBENS a été lancé, on recoit dix fois plus de
mails qu'avant la crise, les serveurs surchauffent un jour sur deux -- encore ce
réchauffement climatique sûrement.

En plus, votre génération ne respecte pas les gestes barrières et la sécurité des
mots de passe. Les majors ont bien dit de désinfecter son clavier 4 fois par jour
et de faire des sauvegardes sur osiris et non hapis.

--------------------------------------------------------------------------------

Fiouf, il aura fallu un peu de TEMPS, mais au moins tu as ton badge.

********************************************************************************
**           Cette action t'a pris 15 minutes et tu as perdu 0 point(s) d'#NRJ.
********************************************************************************
********************************************************************************
**           Il est 10h15. Il te reste 100 d'#NRJ.
********************************************************************************

Tiphaine arrive dans la cuisine du 6ème étage. Jérôme et Pierre sont en train de
parler. Auguste passe. Auguste tousse, mais il est quand même venu.

"Tiphaine, tu devrais déjà être a ton bureau ! Tu es en retard pour notre rendez-vous.

Il faut absolument que t'ailles chercher les données au labo de Nathalie Spassky.

Et viens dans mon bureau tout de suite."

Auguste quitte la cuisine.

--------------------------------------------------------------------------------

ALLER AU RDV :
Tiphaine a un sentiment amer de déjà-vu, mais bon on va faire un effort vu que
c'est le premier jour.

RESTER :
"Ah non, il est relou celui-là. Ca fait littéralement 3 ans que j'ai pas vu Jérôme
et Pierre ! Il peut bien attendre. En plus j'ai rien à lui dire."

--------------------------------------------------------------------------------

Aller au rendez-vous ? (T/F)

F

Auguste parti, Tiphaine entreprend de discuter avec Jérôme et Pierre. De quoi
veut-elle parler ?

--------------------------------------------------------------------------------

LES ECOUTER :
Quoi de neuf ?

LEUR PARLER DE TON DADA DU MOMENT :
Entre pédagogie Montessori et culture hydroponique, ton coeur balance !

--------------------------------------------------------------------------------

Les écouter ? (T/F)T

Jérôme et Pierre sont dans la RESISTANCE ! Ils ont de très forts soupçons contre
le corona-cola. Daoult cherche juste à se remplir les poches et faire la une des
journeaux.

David Holcman est aussi dans le coup avec Pierre Paoletti et une poignée de
doctorant.e.s et de post-doctorant.e.s.

Jérôme et Pierre communiquent à Tiphaine le mot de passe du serveur personnel de
Daoult : LeConsensusCEstPet1

********************************************************************************
**           Cette action t'a pris 20 minutes et tu as perdu 0 point(s) d'#NRJ.
********************************************************************************
********************************************************************************
**           Il est 10h35. Il te reste 100 d'#NRJ.
********************************************************************************

Tiphaine arrive au bureau. Les plantes ont soif. Comme d'hab ! Personne
ne s'en occupe jamais si elle n'est pas là de toute façon...

Un peu de procrastination s'impose.

--------------------------------------------------------------------------------

Par où commencer cette journée de travail intensive ?

1 - Prendre un café
2 - Faire caca
3 - Arroser les plantes

--------------------------------------------------------------------------------

1, 2 ou 3 ?
1
********************************************************************************
**           Cette action t'a pris 5 minutes et tu as gagné 20 point(s) d'#NRJ.
********************************************************************************
Aaaah ! ÇA FAIT DU BIEN !

Enfin un bon café.

Tiphaine se sent BOOSTEE A MORT !

Mais le café... Ça donne un peu envie de faire caca non ?

--------------------------------------------------------------------------------

Réagir au café:

1 - J'ai une mission importante. Pas le temps de faire caca.
2 - J'ai un caca important. Pas le temps de faire ma mission.

--------------------------------------------------------------------------------

 1 ou 2 ? 
2

Tiphaine a bien besoin de faire caca.

Après tout, c'est humain.
Rappelons que Tiphaine est Princesse Cystite !

Elle va donc aux toilettes.

Avant de partir faire sa basse besogne, elle parle longuement à Alexis
Qu'est-ce qu'elle peut avoir comme problèmes intestinaux en ce moment !

Elle a perdu un peu de TEMPS à disserter sur son intestin.
Vite, elle court au toilette.

Là bas, elle s'énerve car 2 ans n'y ont rien changé: Le destructeur
des toilettes de l'IBENS semble toujours à l'oeuvre. Les toilettes sont dégueues.

--------------------------------------------------------------------------------

UN MAIL @ALLBIO :
Afficher ce malotru ! Tu ne peux résister !

PASSER OUTRE :
Tu rages, mais autant se concentrer sur des choses constructives. Plus vite c'est
fait, plus vite tu pourras retrouver tes chèvres.

--------------------------------------------------------------------------------

Un mail @allbio ? (T/F)

TRUE
Ta réponse n'est pas reconnue. [T/F]
T
********************************************************************************
**           Cette action t'a pris 15 minutes et tu as perdu 0 point(s) d'#NRJ.
********************************************************************************
********************************************************************************
**           Cette action t'a pris 5 minutes et tu as perdu -5 point(s) d'#NRJ.
********************************************************************************

Tiphaine se fend d'un long mail à tout allbio.

Elle met une photo en pièce jointe, et rappelle à tout le monde que l'effaçage
des cookies est requis dans le cadre du plan CovIBENS.

Pour appuyer son propos, elle insère également un lien web vers une étude 
scientifique pointant les risques de transmission de COVID-22 par matière fécale.

Un connard lui répond par mail qu'elle est priée de ne plus spammer allbio avec
ses photos de caca.

Tiphaine a perdu un peu de TEMPS et d'#NRJ à rédiger ce mail

Mais elle sait au fond d'elle qu'elle a totalement raison.

--------------------------------------------------------------------------------

Quel sentiment éprouver ?

1 - Ca n'a servi à rien, j'ai perdu du temps, 
    mais je suis fière de moi.

--------------------------------------------------------------------------------

1 ou 1 ?
1

IN THE LAB

alexis = True, hamac_votes = ['ouardia', 'tiphaine', 'alexis']
********************************************************************************
**           Il est 11h00. Il te reste 95 d'#NRJ.
********************************************************************************

Tiphaine a déja fait beaucoup de choses aujourd'hui.

Mais ce n'est pas l'avis d'Auguste qui trouve qu'elle procrastine

Il lui envoie un mail:

                    ******************************
    "Tiphaine,

C'était très drôle tes histoires de Pakistan, mais maintenant y s'agirait de se
sortir les doigts. J'ai pu observer que tu n'as rien fouttu de la matinée."

                    ******************************

En lisant son mail, Tiphaine trouve que ce management tout pourri commence à 
vraiment  lui sortir par le nez. 

S'il y a bien une chose qui ne lui a pas manqué au labo, c'est ça.

Tiphaine peut-elle garder pour elle son agacement ?

--------------------------------------------------------------------------------

GARDER POUR ELLE :
Bah. Il vaut mieux laisser couler, c'est peine perdue de râler.

DIRE A AUGUSTE SES VERITES :
Il est temps que cela cesse. Tiphaine s'énerve et déboule dans le bureau d'Auguste.

--------------------------------------------------------------------------------

Garder pour elle ? (T/F)
F

Auguste n'a vraiment pas changé...

Mais se plaindre ne servirait à rien.

Elle est fatiguée, dommage qu'il n'y ait pas de HAMAC dans ce labo !
Il faut vraiment qu'elle en fasse sa PRIORITE ABSOLUE.

LAB
covid = False, coffee = True, toilets = True, alexis = True
********************************************************************************
**           Il est 11h00. Il te reste 95 d'#NRJ.
********************************************************************************

Ayush et Aurélien injectent du corona-cola sur des neurones de souris in vitro.
Tiphaine est LA data scientist qu’il leur faut. Ayush et Aurélien pensent que le
corona-cola fait dégénérer les neurones mais ils ont besoin d’analyses
quantitatives pour le prouver. Ils lui donnent les images. Pour le reste c’est
bien connu, il “suffit” de faire l’analyse et “y’a qu’à” relancer ses vieux
scripts parce que les données sont GÉNIALES.

Vite vite !

********************************************************************************
**           Cette action t'a pris 30 minutes et tu as perdu 0 point(s) d'#NRJ.
********************************************************************************
********************************************************************************
**           Il est 11h30. Il te reste 95 d'#NRJ.
********************************************************************************

De retour au labo la compétition est rude ! Les GPUs seront départagés par un
tournoi de Pierre-Feuille-Papier-Ciseaux entre Tiphaine, Raphaël, et Lisa.
Seulement deux d'entre elleux pourront accéder aux GPUs.

Tiphaine se concentre pour cette épreuve mentale.

Pierre [0], Papier [1], Ciseaux [2] ?

0

Ca y est ! Tu as enfin un créneau sur les GPUs ! Vite vite, il faut faire ces
analyses pour aider à coincer Daoult.

SHIFUMI
gpu = True
********************************************************************************
**           Il est 11h30. Il te reste 95 d'#NRJ.
********************************************************************************

Bien qu'elle n'ait toujours pas de HAMAC, Tiphaine doit mainenant analyser les données.

C'est facile parce qu'elle a déja fait ce genre de choses plein de fois.

--------------------------------------------------------------------------------

Mais au fait, de quel programme aurait-t-elle besoin dans l'immédiat ?:

1 - PyTorch
2 - Caffe
3 - CellProfiler
4 - memory_manager

--------------------------------------------------------------------------------

Programme (1/2/3/4) ? 
1

Enfin ! Tiphaine a un GPU !

Le CAFE lui donne une super pêche !!

Cela permet à Tiphaine de reconfigurer PyCharm en un rien de temps !

Pour une fois, l'analyse de données se passe SUPER BIEN !

Les données sont propres. Ça ne prend quasiment aucun temps.

Le résultat est formel: Le corona-cola détruit les neurones.
Daoult est un fou de vouloir l'utiliser massivement !

Tiphaine profite de son expérience de chimiste pour examiner la formule chimique
du corona-cola.

OMG !!! LE CORONA-COLA N'EST QUE DE LA BIERE CORONA ET DU COCA !

Le monde doit savoir...

********************************************************************************
**           Cette action t'a pris 30 minutes et tu as gagné 10 point(s) d'#NRJ.
********************************************************************************

ANALYSIS
analysis = True, coffee = True
********************************************************************************
**           Il est 12h00. Il te reste 100 d'#NRJ.
********************************************************************************

Maintenant que Tiphaine a des éléments solides pour affirmer que le corona-cola
est dangereux est inutile, il est urgent qu’elle se trouve des alliés. Elle
choisit d’abord d’en parler à son voisin Alexis.

Alexis écoute Tiphaine silencieusement tout en écrivant son prochain
livre de JDR: “Donjons et Labos”. Le personnage principal de son histoire est
un cheval qui rêve d’être un zèbre. Il répond distraitement à Tiphaine qu’il n’a
pas forcément beaucoup de conseils pour cette histoire de corona-cola mais par
contre lui il a eu plein de problèmes administratifs à son retour, et que c’était
bien relou. Il informe Tiphaine qu’elle aura sûrement du mal avec l’administration
aussi, et qu’elle ne peut pas espérer d’entrevue avec Daoult tant qu’elle n’a pas
régularisé sa situation administrative d’ex-doctorante. Il va falloir qu’elle
recontacte l’administration pour obtenir le formulaire A38 via le laisser-passer A39.

Alexis se propose d'aider Tiphaine en y allant avec elle ce qui accélérera de
beaucoup la quête. Il se pourrait même qu'elle soit disponible à l'heure du déjeuner !

En effet, il a développé un rapport privilégié avec Lina Boitier : il en est même
à lui faire des compliments et des bonnes blagues ;)

Après avoir eu l’avis d’Alexis, elle consulte France.

France écoute Tiphaine soigneusement, prend des notes en hochant studieusement
la tête derrière ses lunettes rondes moches, puis fais un rétro-planning en
rappelant à Tiphaine son TEMPS restant et son #NRJ restante, et le fait que
Daoult doit tenir demain une grande conférence de presse promotionnelle pour le
lancement national du corona-cola et que donc le temps presse.

Elle lui rappelle qu’elle peut faire des siestes pour récupérer de l’énergie,
notamment pour le parcours administratif qui pourrait la tuer de fatigue si elle n’y prend garde.

Ensuite, elle lui propose de convoquer une réunion au sommet au babyfoot,
spécialement aménagé pour faire respecter les gestes barrières. Elle pourrait
profiter d’un grand tournoi pour entendre les avis des uns et des autres et
collecter de précieuses informations sur Daoult, son bureau et ses faiblesses
pour le vaincre.

--------------------------------------------------------------------------------

CONTINUER LA DISCUSSION :
Ca fait deux ans que tu n'as pas vu France. Qu'est-ce qu'elle a bien pu faire
pendant tout ce temps ??

LA REMERCIER :
Tu aimerais bien rester des heures a discuter de la vie, du bon vieux temps, du
feminisme, mais Daout ne sera pas demasque sans rien faire !

--------------------------------------------------------------------------------

Continuer ? [T/F]
T

Tiphaine continue la conversation. Après tout, France
est son amie.

France lui raconte qu’elle a fait beaucoup de sport, qu’elle a publié 7 articles,
qu’elle a perdu 10kg en ne mangeant que des pommes.

Elle donne à Tiphaine du Huel qui permet de restaurer 100% d’#NRJ sans avoir
à perdre de TEMPS, ce qui sera un atout de taille dans le combat contre Daoult.

Dans la conversation, Tiphaine reussi a convaincre France de voter pour le hamac.
En meme temps, France a toujours été pour un coin détente !

Traceback (most recent call last):
  File "rpg.py", line 801, in <module>
    game(DEBUG=True)
  File "rpg.py", line 430, in game
    print_result_action(config.france_dt, config.france_e - energy)
TypeError: unsupported operand type(s) for -: 'int' and 'Energy'

**Comment by Maxime-corbe** [comment]
ah c'est ma faute j'ai pas implémenter le moins... je corrige ça de suite !

**Comment by gldlv** [comment]
On pourrait mettre un menu de jeu (Nouvelle Partie, Crédits, Vidéo introduction, Quitter)

Comme ça on peut faire une boucle principale dans le menu principal

Et si Tiphaine meurt, on, affiche une fonction de mort (t'es DEAD recommence mdr) et on retourne au menu principal ?

**Comment by gldlv** [comment]
Je crois que j'ai résolu les différents problèles avec ba368226f01cc5cbf5acf5259876635eea3f939c à confirmer

**Comment by Maxime-corbe** [comment]
ca a l'air de bien fonctionner, faudra juste faire gaffe a ne pas additionner ou soustraire des nb negatif 10 - (-30) sinon ça va bug ^^
